{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quote-app-ingress
  namespace: quote-app-ns
spec:
  # This specifies that the NGINX ingress controller should handle this Ingress.
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # The name of the Service we want to route traffic to.
            name: quote-app-service
            port:
              # The port number exposed by the Service.
              number: {{ .Values.service.port }}
{{- end -}}