# quote-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app-deployment
  namespace: quote-app-ns
  labels:
    app: quote-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
      - name: quote-app-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: quote-config-volume
          mountPath: /quotes.txt
          subPath: quotes.txt
      volumes:
      - name: quote-config-volume
        configMap:
          name: quote-app-config